---
$schema: https://github.com/hyperledger-labs/fablo/releases/download/2.1.0/schema.json

global:
  fabricVersion: 2.5.9
  tls: false
  engine: docker
  peerDevMode: false

orgs:
  - organization:
      name: Orderer
      domain: orderer.example.com
    orderers:
      - groupName: group1
        type: solo
        instances: 1
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 2
      db: LevelDb
    tools:
      fabloRest: true

channels:
  - name: channel1
    orgs:
      - name: Org1
        peers: [peer0, peer1]

chaincodes: []
